
radiant_add_gamepack(q4
	GAME_TYPE "doom3"
	TITLE "Quake 4"
	GAMEDIR "q4base"
	PATH_WIN32 "C:/Program Files/id Software/Quake 4/"
	PATH_LINUX "/usr/local/games/quake4/"
	PATH_MACOS "/Applications/Quake4/"
	EXECUTABLE_WIN32 "Quake4.exe"
	EXECUTABLE_LINUX "Quake4"
	EXECUTABLE_MACOS "Quake4.app"
	SHADER_TYPE "quake4"
	SHADER_PATH "materials"
	ENTITY_CLASS "doom3"
	ENTITIES "doom3"
	ARCHIVE_TYPES "pk4"
	TEXTURE_TYPES "tga" "jpg" "dds"
	MODEL_TYPES "lwo" "ase" "md5mesh"
	SOUND_TYPES "wav"
	MAP_TYPES "mapquake4"
	BRUSH_TYPES "quake4"
	PATCH_TYPES "doom3" "def2doom3"
	DEFAULT_SCALE "0.5"
	SUPPORT_PATCHES
)
