if(NOT RADIANT_BUILD_H2DATA)
	return()
endif()

radiant_add_tool(h2data
	SOURCES
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/bspfile.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/cmdlib.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/inout.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/l3dslib.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/lbmlib.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/mathlib.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/md4.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/path_init.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/qfiles.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/scriplib.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/threads.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/token.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common/trilib.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/qcommon/reference.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/qcommon/resourcemanager.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/qcommon/skeletons.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/animcomp.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/book.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/fmodels.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/images.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/jointed.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/models.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/pics.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/qdata.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/qd_skeletons.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/sprites.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/svdcmp.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/tables.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/tmix.c
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/video.c
	INCLUDE_DIRECTORIES
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/common
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2/qcommon
		${PROJECT_SOURCE_DIR}/tools/quake2/qdata_heretic2
		${PROJECT_SOURCE_DIR}/tools/quake2/common
		${PROJECT_SOURCE_DIR}/include
		${PROJECT_SOURCE_DIR}/libs
	DEPENDENCIES
		wiferadiant-library-l_net
		$<$<BOOL:${WIN32}>:ws2_32>
		LibXml2::LibXml2
		$<TARGET_NAME_IF_EXISTS:Math::Math>
)
