if(NOT RADIANT_BUILD_WRMAP)
	return()
endif()

if(WIN32)
	set(WRMAP_RC_ORIGINAL_FILENAME "wrmap.${RADIANT_EXECUTABLE_SUFFIX}")
	set(WRMAP_RC_ICON_FILENAME "${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/wrmap.ico")
	set(WRMAP_RC_FILEVERSION "${WRMAP_VERSION_MAJOR},${WRMAP_VERSION_MINOR},${WRMAP_VERSION_PATCH},0")
	configure_file("${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/wrmap.rc.in" "${PROJECT_BINARY_DIR}/wrmap.rc" @ONLY)
endif()

radiant_add_tool(wrmap
	SOURCES
		${PROJECT_SOURCE_DIR}/tools/quake3/common/cmdlib.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/qimagelib.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/inout.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/md4.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/mutex.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/polylib.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/scriplib.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/threads.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/unzip.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/vfs.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/common/miniz.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/autopk3.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/brush.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/bspfile_abstract.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/bspfile_ibsp.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/bspfile_rbsp.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/bsp.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/convert_ase.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/convert_bsp.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/convert_json.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/convert_map.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/convert_obj.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/decals.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/exportents.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/facebsp.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/fog.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/games.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/help.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/image.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/leakfile.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/light_bounce.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/lightmaps_ydnar.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/light.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/light_trace.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/light_ydnar.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/main.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/map.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/minimap.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/mesh.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/model.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/patch.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/path_init.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/portals.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/prtfile.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/shaders.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/surface_extra.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/surface_foliage.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/surface_fur.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/surface_meta.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/surface.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/tjunction.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/tree.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/visflow.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/vis.cpp
		${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/writebsp.cpp
		$<$<BOOL:${WIN32}>:${PROJECT_BINARY_DIR}/wrmap.rc>
		$<$<BOOL:${WRMAP_WITH_ERICWTOOLS}>:${PROJECT_SOURCE_DIR}/tools/quake3/q3map2/ewt.cpp>
	DEPENDENCIES
		wiferadiant-library-l_net
		wiferadiant-library-filematch
		wiferadiant-library-ddslib
		wiferadiant-library-etclib
		wiferadiant-library-crnlib
		wiferadiant-library-webplib
		wiferadiant-library-stb
		pugixml::pugixml
		assimp
		gamepacklib
		$<$<BOOL:${WIN32}>:ws2_32>
		$<$<BOOL:${WRMAP_WITH_ERICWTOOLS}>:libqbsp>
		$<$<BOOL:${WRMAP_WITH_ERICWTOOLS}>:libvis>
		$<$<BOOL:${WRMAP_WITH_ERICWTOOLS}>:liblight>
	INCLUDE_DIRECTORIES
		${PROJECT_SOURCE_DIR}/include
		${PROJECT_SOURCE_DIR}/libs
		${PROJECT_SOURCE_DIR}/tools/quake3/common
	COMPILE_DEFINITIONS
		$<$<BOOL:${WRMAP_WITH_ERICWTOOLS}>:USE_ERICWTOOLS>
	COMPILE_OPTIONS
		$<$<CXX_COMPILER_ID:GNU,Clang>:-Wno-dangling-pointer>
)
