
if(WIN32)
	set(RADIANT_EXECUTABLE_SUFFIX "exe")
	set(RADIANT_LIBRARY_SUFFIX "dll")
elseif(EMSCRIPTEN)
	set(RADIANT_EXECUTABLE_SUFFIX "wasm")
	set(RADIANT_LIBRARY_SUFFIX "wasm")
elseif(CMAKE_SYSTEM_PROCESSOR)
	string(TOLOWER ${CMAKE_SYSTEM_PROCESSOR} _system_processor)
	set(RADIANT_EXECUTABLE_SUFFIX ${_system_processor}${CMAKE_EXECUTABLE_SUFFIX})
	set(RADIANT_LIBRARY_SUFFIX ${_system_processor}${CMAKE_SHARED_LIBRARY_SUFFIX})
endif()

set(RADIANT_COMMON_OPTIONS
	$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-Wreorder>
	$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-fno-rtti>
	$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-fpermissive>
	$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<C_COMPILER_ID:GNU,Clang>>:-W>
	$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<C_COMPILER_ID:GNU,Clang>>:-Wall>
	$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<C_COMPILER_ID:GNU,Clang>>:-Wcast-align>
	$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<C_COMPILER_ID:GNU,Clang>>:-Wcast-qual>
	$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<C_COMPILER_ID:GNU,Clang>>:-Wno-unused-parameter>
	$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<C_COMPILER_ID:GNU,Clang>>:-Wno-unused-function>
	$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:GNU,Clang>>:-fno-strict-aliasing>
)

set(RADIANT_COMMON_DEFINITIONS
	QT_NO_KEYWORDS
	RADIANT_VERSION=\"${RADIANT_VERSION}\"
	RADIANT_MAJOR_VERSION=\"${RADIANT_MAJOR_VERSION}\"
	RADIANT_MINOR_VERSION=\"${RADIANT_MINOR_VERSION}\"
	RADIANT_PATCH_VERSION=\"${RADIANT_PATCH_VERSION}\"
	RADIANT_ABOUTMSG=\"${RADIANT_ABOUTMSG}\"
	$<$<CONFIG:Debug>:_DEBUG>
	$<$<NOT:$<BOOL:${WIN32}>>:POSIX>
	$<$<BOOL:${WIN32}>:WIN32>
	RADIANT_EXECUTABLE_SUFFIX=\"${RADIANT_EXECUTABLE_SUFFIX}\"
	RADIANT_LIBRARY_SUFFIX=\"${RADIANT_LIBRARY_SUFFIX}\"
	WRMAP_VERSION=\"${WRMAP_VERSION}\"
	WRMAP_MOTD=\"${WRMAP_MOTD}\"
	Q3MAP_VERSION=\"${Q3MAP_VERSION}\"
	Q3MAP_MOTD=\"${Q3MAP_MOTD}\"
)
